global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - "192.168.0.190:9100"

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - "192.168.0.190:8081"

  - job_name: 'Linux-Servers'
    metrics_path: /metrics
    file_sd_configs:
      - files:
        - '/etc/prometheus/Linux_Servers.yml'

  - job_name: 'Windows-Servers'         # ðŸ‘ˆ New Windows job
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - '/etc/prometheus/Windows_Servers.yml'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
#           - http://app.deployflow.tech/
#          - https://cloudracing.svaapta.com
#          - https://app.cloudracing.com
           - https://github.com
#          - https://compare.group
#          - https://web.whizzq.app
#          - https://api.whizzq.app
#          - https://web.whizzq.app/
#          - https://schedule.dynamicpginc.com/
#          - https://staging-schedule.dynamicpginc.com/
#          - https://schedule-overwatch.com/
#          - https://staging-overwatch.dynamicpginc.com/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.0.190:9115
